version: '3.3'
services:

  backend:
    image: plone/plone-backend:6.0.1
    # Plone 5.2 series can be used too
    # image: plone/plone-backend:5.2.10
    ports:
      - '8080:8080'
    environment:
      - SITE=Plone
      - 'PROFILES=plone.volto:default-homepage'
      - CORS_ALLOW_ORIGIN=http://plone.localhost
    labels:
      - traefik.enable=true
      # SERVICE
      - traefik.http.services.plone-backend.loadbalancer.server.port=8080
      # Plone API
      - traefik.http.routers.backend.rule=(Host(`plone.localhost`) && PathPrefix(`/++api++`))
      - traefik.http.routers.backend2.rule=(Host(`plone2.localhost`) && PathPrefix(`/++api++`))
      - traefik.http.routers.backend.service=plone-backend
      - "traefik.http.middlewares.backend.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
      - "traefik.http.middlewares.backend.replacepathregex.replacement=/VirtualHostBase/http/plone.localhost/Plone/++api++/VirtualHostRoot/$$1"
      - "traefik.http.middlewares.backend2.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
      - "traefik.http.middlewares.backend2.replacepathregex.replacement=/VirtualHostBase/http/plone2.localhost/Plone2/++api++/VirtualHostRoot/$$1"
      - traefik.http.routers.backend.middlewares=gzip,backend
      - traefik.http.routers.backend2.middlewares=gzip,backend2

  frontend:
    # image: 'plone/plone-frontend:latest'
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
      - '3001:3001'
    restart: always
    #environment:
      # This last is not required if a reverse proxy is in the stack
      #RAZZLE_API_PATH: http://plone.localhost
    volumes:
      - ./src/:/app/src
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      # SERVICE
      - traefik.http.services.plone-frontend.loadbalancer.server.port=3000
      # HOSTS: Main
      - traefik.http.routers.frontend.rule=Host(`plone.localhost`)
      - traefik.http.routers.frontend2.rule=Host(`plone2.localhost`)
      - traefik.http.routers.frontend.service=plone-frontend
      - traefik.http.routers.frontend2.service=plone-frontend
      - traefik.http.middlewares.apiPathHeaders.headers.customrequestheaders.X-Api-Path=http://plone.localhost
      - traefik.http.middlewares.apiPathHeaders.headers.customrequestheaders.X-Internal-Api-Path=http://backend:8080/Plone
      - traefik.http.middlewares.apiPathHeaders2.headers.customrequestheaders.X-Api-Path=http://plone2.localhost
      - traefik.http.middlewares.apiPathHeaders2.headers.customrequestheaders.X-Internal-Api-Path=http://backend:8080/Plone2
      - traefik.http.routers.frontend.middlewares=apiPathHeaders
      - traefik.http.routers.frontend2.middlewares=apiPathHeaders2
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    depends_on:
      - frontend
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8888:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2
