site_name: Volto Developer Documentation
docs_dir: ./source
site_dir: ./build
repo_url: 'https://github.com/plone/volto'
copyright: 'Made with ❤️ by the Plone Community - All code owned by the Plone Foundation'
theme:
  name: 'material'
#   custom_dir: 'theme'
  logo: 'images/volto-h-transparent.svg'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'red'
  font:
    text: 'Montserrat'
    code: 'Source Code Pro'
extra_css:
  - 'stylesheets/extra.oct2020.css'
  - 'stylesheets/pygments.css'

nav:
  - Getting Started:
      - Bootstrap Volto: 'getting-started/install.md'
      - Developer roadmap: 'getting-started/roadmap.md'
      - Learning resources: 'getting-started/others.md'
      - How does it work under the hood: 'getting-started/howdoesitwork.md'
  - Design principles: 'design-principles/index.md'
  - Style Guide: 'style-guide/index.md'
  - Configuration:
      - What is configurable?: 'configuration/how-to.md'
      - Settings reference guide: 'configuration/settings-reference.md'
      - Zero config builds: 'configuration/zero-config-builds.md'
      - Internal proxy: 'configuration/internalproxy.md'
      - Backend configuration: 'configuration/backend.md'
      - Richeditor settings: 'configuration/richeditor-settings.md'
      - Multilingual: 'configuration/multilingual.md'
      - Working copy: 'configuration/workingcopy.md'
      - Environment variables: 'configuration/environmentvariables.md'
      - API expanders: 'configuration/expanders.md'
  - Theming & Semantic UI:
      - About Semantic UI: 'theming/about-semantic.md'
      - Semantic UI Theming: 'theming/semanticui-theming.md'
      - Theming Engine: 'theming/theming-engine.md'
      - Theming strategy: 'theming/theming-strategy.md'
      - Custom styling: 'theming/custom-styling.md'
      - Use another theming engine: 'theming/using-third-party-themes.md'
  - Development recipes:
      - Creating a project: 'recipes/creating-project.md'
      - Folder structure: 'recipes/folder-structure.md'
      - Customizing components: 'recipes/customizing-components.md'
      - Customizing views: 'recipes/customizing-views.md'
      - Creating new views: 'recipes/creating-views.md'
      - Internationalization: 'recipes/i18n.md'
      - Express middleware: 'recipes/express.md'
      - Lazy loading and code splitting: 'recipes/lazyload.md'
      - Overriding i18n messages: 'recipes/overridei18n.md'
      - App component insertion point: 'recipes/appextras.md'
      - Context navigation component: 'recipes/contextnavigation.md'
      - Pluggables: 'recipes/pluggables.md'
      - Forms and widgets: 'recipes/widget.md'
  - Blocks:
      - Introduction: 'blocks/introduction.md'
      - Anatomy: 'blocks/anatomy.md'
      - Settings: 'blocks/settings.md'
      - Edit components: 'blocks/editcomponent.md'
      - Extensions: 'blocks/extensions.md'
      - SSR: 'blocks/ssr.md'
  - Addons:
      - Introduction: 'addons/index.md'
      - Internationalization: 'addons/i18n.md'
      - Best practices: 'addons/best-practices.md'
  - Backend integration: 'backend/index.md'
  - Deploying:
      - Simple deployment: 'deploying/simple.md'
      - Using PM2: 'deploying/pm2.md'
      - Seamless mode: 'deploying/seamless-mode.md'
      - Using apache: 'deploying/apache.md'
      - Using sentry: 'deploying/sentry.md'
      - Performance improvements: 'deploying/performance.md'
  - Upgrade Guide: 'upgrade-guide/index.md'
  - Developer Guidelines:
      - Language features: 'developer-guidelines/language-features.md'
      - Linting: 'developer-guidelines/linting.md'
      - React: 'developer-guidelines/react.md'
      - Redux: 'developer-guidelines/redux.md'
      - Routing: 'developer-guidelines/routing.md'
      - Testing: 'developer-guidelines/testing.md'
      - Acceptance tests: 'developer-guidelines/acceptance-tests.md'
      - Accessibility: 'developer-guidelines/accessibility-guidelines.md'
  - Contributing:
      - Guidelines: 'contributing/guidelines.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      permalink: '#'
  - markdown.extensions.def_list
  - pymdownx.tilde
