site_name: Volto Developer Documentation
docs_dir: ./source
site_dir: ./build
repo_url: 'https://github.com/plone/volto'
copyright: 'Made with ❤️ by the Plone Community - All code owned by the Plone Foundation'
theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'images/volto-h-transparent.svg'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'teal'
    accent: 'red'
  font:
    text: 'Poppins'
    code: 'Source Code Pro'
extra_css:
  - 'stylesheets/extra.css'

nav:
  - Getting Started: 'getting-started/install.md'
  - Design principles: 'design-principles/index.md'
  - Configuration:
      - What is configurable?: 'configuration/how-to.md'
      - Settings reference guide: 'configuration/settings-reference.md'
      - Internal proxy: 'configuration/internalproxy.md'
      - Richeditor settings: 'configuration/richeditor-settings.md'
      - Multilingual: 'configuration/multilingual.md'
  - Semantic UI:
      - About Semantic UI: 'semantic-ui/about-semantic.md'
      - Semantic UI Theming: 'semantic-ui/semanticui-theming.md'
      - Theming Engine: 'semantic-ui/theming-engine.md'
  - Theming:
      - Theming strategy: 'theming/theming-strategy.md'
      - Custom styling: 'theming/custom-styling.md'
      - Intregrate third party: 'theming/integrate-third-party.md'
  - Customizing:
      - Creating a project: 'customizing/creating-project.md'
      - Folder structure: 'customizing/folder-structure.md'
      - Customizing components: 'customizing/customizing-components.md'
      - Customizing views: 'customizing/customizing-views.md'
      - Creating new views: 'customizing/creating-views.md'
      - Creating Add-on packages: 'customizing/add-ons.md'
      - Internationalization: 'customizing/i18n.md'
      - Express middleware: 'customizing/express.md'
  - Blocks:
      - Introduction: 'blocks/introduction.md'
      - Anatomy: 'blocks/anatomy.md'
      - Settings: 'blocks/settings.md'
      - Edit components: 'blocks/editcomponent.md'
  - Recipes:
      - App component insertion point: 'recipes/appextras.md'
      - Lazy loading and code splitting: 'recipes/lazyload.md'
      - Overriding i18n messages: 'recipes/overridei18n.md'
  - Deploying:
      - Simple deployment: 'deploying/simple.md'
      - Using PM2: 'deploying/pm2.md'
      - Using apache: 'deploying/apache.md'
      - Using sentry: 'deploying/sentry.md'
  - Upgrade Guide: 'upgrade-guide/index.md'
  - Developer Guidelines:
      - Accessibility: 'developer-guidelines/accessibility-guidelines.md'
      - React: 'developer-guidelines/react.md'
      - Babel: 'developer-guidelines/babel.md'
      - Redux: 'developer-guidelines/redux.md'
      - Routing: 'developer-guidelines/routing.md'
      - Linting: 'developer-guidelines/linting.md'
      - Language features: 'developer-guidelines/language-features.md'
      - Acceptance tests: 'developer-guidelines/acceptance-tests.md'
  - Contributing:
      - Guidelines: 'contributing/guidelines.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      permalink: '#'
