name: Volto CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: debug
      working-directory: api
      run: ls -al
    # node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # node cache
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    # node install
    - run: yarn install --frozen-lockfile
    - run: yarn run prettier
    - run: yarn run lint
    - run: yarn run code-analysis:i18n
    - run: yarn test:ci
    # python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # python cache
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # python install
    - name: debug
      working-directory: api
      run: ls -al
    - run: pip install virtualenv
    - name: create virtualenv
      working-directory: api
      run: virtualenv --clear --python=python3 .
    - name: debug
      working-directory: api
      run: ls -al
    - name: debug
      run: ls -al
    - name: debug
      working-directory: api
      run: ls -al
    - name: pip install
      working-directory: api
      run: bin/pip install -r requirements.txt
    - name: buildout
      working-directory: api
      run: bin/buildout
      env:
        CI: true