name: Cookieplone
on: [push, pull_request]

env:
  PYTHON_VERSION: "3.13"

jobs:
  seven:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    name: Seven Cookieplone
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - run: echo "Current branch is ${GITHUB_REF#refs/heads/}"
      - name: Set up Node.js environment
        uses: ./.github/actions/node_env_setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Cookieplone-based frontend addon
        run: |
          pipx install cookieplone
          COOKIEPLONE_REPOSITORY_TAG=seventemplate pipx run --no-cache cookieplone seven_addon --no-input

      - name: Install generated package
        working-directory: seven-add-on
        run: |
          pnpm dlx mrs-developer missdev --no-config --fetch-https
          (cd core && git fetch --depth 1 origin ${GITHUB_REF#refs/heads/}:${GITHUB_REF#refs/heads/} && git checkout ${GITHUB_REF#refs/heads/})
          pnpm i
          make build-deps

      - name: Run ESlint in the generated package
        working-directory: seven-add-on
        run: pnpm lint

      - name: Run Prettier in the generated package
        working-directory: seven-add-on
        run: pnpm prettier

      - name: Run Stylelint in the generated package
        working-directory: seven-add-on
        run: pnpm stylelint

      - name: Cypress acceptance tests
        uses: cypress-io/github-action@v6
        env:
          BABEL_ENV: production
          CYPRESS_RETRIES: 2
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: false
          working-directory: seven-add-on/core/apps/seven
          browser: chrome
          spec: cypress/tests/core/basic/**/*.cy.ts
          start: |
            make ci-acceptance-backend-start
            make project-acceptance-frontend-prod-start
          wait-on: 'npx wait-on --httpTimeout 20000 http-get://127.0.0.1:55001/plone http://127.0.0.1:3000'

      # Upload Cypress screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/seven/cypress/screenshots
      # Upload Cypress videos
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: apps/seven/cypress/videos
