# This workflow checks issues and PRs that have had no activity for a
# specified amount of time. You can adjust the behavior by modifying this file.
# For more information, see:
#   https://github.com/actions/stale
---
name: 'Stale Items Policy'
on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: 'ðŸ§¹ Mark stale issues and PRs'
        id: stale_items
        uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 180
          days-before-close: -1 # never close issues and prs
          stale-issue-label: '30.1 needs: confirmation'
          stale-pr-label: '30.1 needs: confirmation'
          operations-per-run: 50
